### ISSUE TITLE
Cannot open on MacOS Sonoma 14.5 (Intel)

### ISSUE THREAD

**Issue by nothing2obvi** [nhershy/CorruptVideoFileInspector#28]
Upon opening `/Applications/Corrupt Video Inspector.app/Contents/MacOS/CorruptVideoInspector` I get the following:

```
/Applications/Corrupt\ Video\ Inspector.app/Contents/MacOS/CorruptVideoInspector ; exit;
redacted@Redacteds-Mac-mini ~ % /Applications/Corrupt\ Video\ Inspector.app/Contents/MacOS/CorruptVideoInspector ; exit;
Traceback (most recent call last):
  File "/Applications/Corrupt Video Inspector.app/Contents/Resources/__boot__.py", line 170, in <module>
    _run()
  File "/Applications/Corrupt Video Inspector.app/Contents/Resources/__boot__.py", line 84, in _run
    exec(compile(source, path, "exec"), globals(), globals())
  File "/Applications/Corrupt Video Inspector.app/Contents/Resources/CorruptVideoInspector.py", line 7, in <module>
    import psutil
  File "psutil/__init__.pyc", line 123, in <module>
  File "psutil/_psosx.pyc", line 13, in <module>
  File "psutil/_psposix.pyc", line 28, in <module>
  File "psutil/_psutil_osx.pyc", line 14, in <module>
  File "psutil/_psutil_osx.pyc", line 10, in __load
  File "imp.pyc", line 343, in load_dynamic
ImportError: dlopen(/Applications/Corrupt Video Inspector.app/Contents/Resources/lib/python3.10/lib-dynload/psutil/_psutil_osx.so, 0x0002): tried: '/Applications/Corrupt Video Inspector.app/Contents/Resources/lib/python3.10/lib-dynload/psutil/_psutil_osx.so' (mach-o file, but is an incompatible architecture (have 'arm64', need 'x86_64h' or 'x86_64')), '/System/Volumes/Preboot/Cryptexes/OS/Applications/Corrupt Video Inspector.app/Contents/Resources/lib/python3.10/lib-dynload/psutil/_psutil_osx.so' (no such file), '/Applications/Corrupt Video Inspector.app/Contents/Resources/lib/python3.10/lib-dynload/psutil/_psutil_osx.so' (mach-o file, but is an incompatible architecture (have 'arm64', need 'x86_64h' or 'x86_64'))
2024-11-02 16:55:52.038 CorruptVideoInspector[12675:315908] Launch error
2024-11-02 16:55:52.038 CorruptVideoInspector[12675:315908] Launch error
See the py2app website for debugging launch issues

Saving session...
...copying shared history...
...saving history...truncating history files...
...completed.

[Process completed]
```

![Screenshot 2024-11-02 at 4 56 04 PM](https://github.com/user-attachments/assets/251b93d9-73ec-4ae0-8f03-5caeb1e6ad29)

**Comment by deepou** [comment]
Same problem here.

**Comment by nhershy** [comment]
You guys shouldn't be drilling down into the application folder (going into Contents, MacOS, etc). Simply, double click the dmg, and drag the "Corrupt Video Inspector" into the Applications folder. 

Then close / delete the .dmg file. After, just go to the Applications folder and double click the app to run.

**Comment by deepou** [comment]
I did exactly that first...on Sonoma (14.6.1 Intel)...got the same "Launch Error" popup window (only after that did I try to dig deeper).

**Comment by teslasparks301** [comment]
Is there any resolution for this? I DLed the app today and installed it. When I launched it from Applications, I got the error window shown in the OP. I went to the web site via the button in the error window which suggested I launch from the command line. That gave me the same output shown in the OP. What to do?
